### ISSUE TITLE
Unable to use get for all data inside my react state

### ISSUE THREAD

**Issue by syedsimanta03** [travist/resourcejs#107]
**ERR**
```
{message: "Request failed with status code 500", name: "Error", description: undefined, number: undefined, fileName: undefined, …}
code: undefined
columnNumber: undefined
config:
adapter: ƒ xhrAdapter(config)
data: undefined
headers: {Accept: "application/json, text/plain, */*"}
maxContentLength: -1
method: "get"
timeout: 0
transformRequest: [ƒ]
transformResponse: [ƒ]
url: "/book"
validateStatus: ƒ validateStatus(status)
xsrfCookieName: "XSRF-TOKEN"
xsrfHeaderName: "X-XSRF-TOKEN"
__proto__: Object
description: undefined
fileName: undefined
lineNumber: undefined
message: "Request failed with status code 500"
name: "Error"
number: undefined
stack: "Error: Request failed with status code 500↵    at createError (http://localhost:3000/static/js/0.chunk.js:46032:15)↵    at settle (http://localhost:3000/static/js/0.chunk.js:46253:12)↵    at XMLHttpRequest.handleLoad (http://localhost:3000/static/js/0.chunk.js:45507:7)"
__proto__: Object
```

server using 5000port react proxy enabled linked to 5000

postman is able to fetch but react is unable with axios...I'm getting error 500 on GET /resource requests, when resources is empty collection in MongoDB.

**Comment by Sefriol** [comment]
Most likely related: https://github.com/travist/resourcejs/issues/71
